main:
  build: .
  ports:
  - 80:5000
  - 443:5000
  environment:
    - MONGO_URL
  links:
    - mongo

mongo:
  image: "mongo"
  environment:
      - "LINK_SCHEME=mongo"
      - "LINK_PATH=/sessions-dev"
  ports:
    - 27017:27017
