main:
  build: .
  ports:
    - 80:3000
    - 443:3000
  environment:
    - MONGO_URL
  links:
    - mongo
mongo:
  image: mongo
  environment:
    - LINK_SCHEME=mongodb
    - LINK_PATH=/sessions-dev
  ports:
    - 27017:27017
